ARCH=(
  adw-gtk-theme
  adwaita-icon-theme
  ananicy-cpp
  base-devel
  bluez-utils
  btrfs-assistant
  cachyos-ananicy-rules
  cachyos-settings
  clonezilla
  dkms
  flatpak
  gdm
  ghostty
  git
  glib2-devel
  gnome-browser-connector
  gnome-control-center
  gnome-keyring
  gnome-session
  gnome-settings-daemon
  gnome-shell
  gnome-themes-extra
  gpaste
  gufw
  gvfs
  ifuse
  imagemagick
  imwheel
  iptables-nft
  keepass
  libinput-gestures
  libsecret
  linux-cachyos
  linux-cachyos-headers
  linux-cachyos-lts-lto
  linux-cachyos-lts-lto-headers
  mesa
  mission-center
  nautilus
  networkmanager
  paru #build-only
  pipewire
  pipewire-pulse
  plymouth
  ptyxis
  python-setuptools
  python-six #rabbit-vcs
  qbittorrent
  scx-managerS
  scx-scheds
  scx-tools
  sushi
  systemdgenie
  ufw
  wireplumber
  xdg-desktop-portal-gnome
  ydotool
  zsh
)

AUR=(
  brave-origin-beta-bin
  gnome-rounded-blur
  grub-customizer
  input-remapper-bin
  jopdf
  nautilus-copy-path
  rabbitvcs-nautilus
  vscodium-insiders-bin
  xdg-terminal-exec
)
